---
- hosts: "{{ HOSTS }}"
  become: true
  vars:
    report_server: rhel1

  tasks:
    # Install yum-utils if it's not there
    - name: Install yum-utils
      ansible.builtin.dnf:
        name: yum-utils
        state: installed

    - name: Include Patching Role
      ansible.builtin.include_role:
        name: "../collections/ansible_collections/demo/patching/roles/patch_linux"

    - name: Deploy report server
      delegate_to: "{{ report_server }}"
      run_once: true  # noqa: run-once[task]
      block:
        - name: Install firewall dependencies
          ansible.builtin.dnf:
            name:
              - firewalld
              - python3-firewall
            state: present

        - name: Start firewalld
          ansible.builtin.service:
            name: firewalld
            state: started

        - name: Enable firewall http service
          ansible.posix.firewalld:
            service: '{{ item }}'
            state: enabled
            immediate: true
            permanent: true
          loop:
            - http
            - https

        - name: Build report server
          ansible.builtin.include_role:
            name: "{{ item }}"
          loop:
            - "../collections/ansible_collections/demo/patching/roles/report_server"
            - "../collections/ansible_collections/demo/patching/roles/report_linux"
            - "../collections/ansible_collections/demo/patching/roles/report_linux_patching"

        - name: Publish report landing page
          ansible.builtin.include_role:
            name: "../collections/ansible_collections/demo/patching/roles/report_server"
            tasks_from: linux_landing_page
